-- =========================================================================
-- KỊCH BẢN KHỞI TẠO CƠ SỞ DỮ LIỆU POSTGRESQL TRỌN GÓI CHO THCS YÊN BÌNH
-- Sao chép toàn bộ mã SQL này -> Dán vào Supabase Dashboard: SQL Editor -> Run
-- =========================================================================

-- -------------------------------------------------------------------------
-- PHẦN 1: TẠO TẤT CẢ CÁC BẢNG DỮ LIỆU (CREATE TABLES FIRST)
-- -------------------------------------------------------------------------

-- 1. BẢNG NGƯỜI DÙNG & THÀNH VIÊN (users)
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'GIAO_VIEN',
  email TEXT DEFAULT '',
  status TEXT NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. BẢNG CHUYÊN MỤC TIN TỨC (categories)
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  icon TEXT DEFAULT 'Newspaper',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. BẢNG BÀI VIẾT TIN TỨC & SỰ KIỆN (articles)
CREATE TABLE IF NOT EXISTS public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  category_name TEXT DEFAULT 'Tin tức - Sự kiện',
  summary TEXT DEFAULT '',
  content TEXT DEFAULT '',
  image TEXT DEFAULT '',
  file_url TEXT DEFAULT '',
  external_link TEXT DEFAULT '',
  author TEXT DEFAULT 'Ban Biên Tập THCS Yên Bình',
  is_featured INT DEFAULT 0,
  views INT DEFAULT 120,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. BẢNG VĂN BẢN CHỈ ĐẠO & QUY CHẾ (documents)
CREATE TABLE IF NOT EXISTS public.documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'Thông tư BGD&ĐT',
  issue_date TEXT NOT NULL,
  signer TEXT DEFAULT 'THCS Yên Bình',
  file_url TEXT DEFAULT '',
  file_name TEXT DEFAULT '',
  external_link TEXT DEFAULT '',
  views INT DEFAULT 4500,
  downloads INT DEFAULT 1700,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. BẢNG THƯ VIỆN VIDEO (videos)
CREATE TABLE IF NOT EXISTS public.videos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  youtube_id TEXT DEFAULT '',
  thumbnail_url TEXT DEFAULT '',
  video_url TEXT DEFAULT '',
  external_link TEXT DEFAULT '',
  views INT DEFAULT 890,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. BẢNG THƯ VIỆN ALBUMS ẢNH (albums)
CREATE TABLE IF NOT EXISTS public.albums (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT DEFAULT '08/08/2026',
  photos_count INT DEFAULT 10,
  cover TEXT DEFAULT '',
  description TEXT DEFAULT '',
  file_url TEXT DEFAULT '',
  external_link TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. BẢNG KHO TÀI NGUYÊN & ĐỀ THI (resources)
CREATE TABLE IF NOT EXISTS public.resources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT DEFAULT 'Đề thi & Đáp án',
  subject TEXT DEFAULT 'Toán 9',
  author TEXT DEFAULT 'Tổ Chuyên Môn',
  date TEXT DEFAULT '08/08/2026',
  downloads INT DEFAULT 450,
  file_url TEXT DEFAULT '',
  file_name TEXT DEFAULT '',
  external_link TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. BẢNG LỊCH CÔNG TÁC TUẦN (schedules)
CREATE TABLE IF NOT EXISTS public.schedules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  day_title TEXT NOT NULL,
  time_slot TEXT NOT NULL,
  content TEXT NOT NULL,
  leader TEXT DEFAULT 'Ban Giám Hiệu',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. BẢNG THÔNG BÁO CHỮ CHẠY (announcements)
CREATE TABLE IF NOT EXISTS public.announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  link TEXT DEFAULT '',
  priority INT DEFAULT 1,
  is_active INT DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. BẢNG CẤU HÌNH TRƯỜNG HỌC & BANNER (site_config)
CREATE TABLE IF NOT EXISTS public.site_config (
  id INT PRIMARY KEY DEFAULT 1,
  school_name TEXT DEFAULT 'TRƯỜNG THCS YÊN BÌNH',
  governing_body TEXT DEFAULT 'ỦY BAN NHÂN DÂN XÃ YÊN BÌNH - TỈNH LẠNG SƠN',
  slogan TEXT DEFAULT 'HỘI TỤ - KẾT TINH - TỎA SÁNG',
  address TEXT DEFAULT 'Xã Yên Bình - Tỉnh Lạng Sơn',
  phone TEXT DEFAULT '(0205) 3885.6789',
  email TEXT DEFAULT 'thcsyenbinh.huulung@langson.edu.vn',
  logo_url TEXT DEFAULT '/images/school-logo.jpg',
  banner_bg TEXT DEFAULT '/images/school-banner.png',
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- -------------------------------------------------------------------------
-- PHẦN 2: MỞ QUYỀN TRUY CẬP ĐỂ TẤT CẢ THIẾT BỊ ĐỀU TẢI & ĐỒNG BỘ ĐƯỢC
-- -------------------------------------------------------------------------

ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.articles DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.videos DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.albums DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_config DISABLE ROW LEVEL SECURITY;

-- -------------------------------------------------------------------------
-- PHẦN 3: NẠP DỮ LIỆU MẪU BAN ĐẦU CHO THCS YÊN BÌNH
-- -------------------------------------------------------------------------

INSERT INTO public.categories (id, name, slug, icon) VALUES
(1, 'Tin tức - Sự kiện', 'tin-tuc-su-kien', 'Newspaper'),
(2, 'Hoạt động chuyên môn', 'hoat-dong-chuyen-mon', 'BookOpen'),
(3, 'Hoạt động đoàn thể', 'hoat-dong-doan-the', 'Users'),
(4, 'Hoạt động ngoại khóa', 'hoat-dong-ngoai-khoa', 'Sparkles'),
(5, 'Câu lạc bộ', 'cau-lac-bo', 'Trophy')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.users (id, username, password, full_name, role, email, status) VALUES
(1, 'admin', '$2a$10$84J.N1i1JvCjJmI/K2D/Me1M.Kx7XG1t3VnS3bK7V9tL.u8.k1u.', 'Thầy Hiệu Trưởng - THCS Yên Bình', 'BGH', 'bgh.thcsyenbinh@langson.edu.vn', 'ACTIVE'),
(2, 'giaovien', '$2a$10$84J.N1i1JvCjJmI/K2D/Me1M.Kx7XG1t3VnS3bK7V9tL.u8.k1u.', 'Cô Nguyễn Thị Hoa - Giáo Viên Văn', 'GIAO_VIEN', 'hoanguyen@thcsyenbinh.edu.vn', 'ACTIVE')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.site_config (id, school_name, governing_body, slogan, address, phone, email, logo_url, banner_bg) VALUES
(1, 'TRƯỜNG THCS YÊN BÌNH', 'ỦY BAN NHÂN DÂN XÃ YÊN BÌNH - TỈNH LẠNG SƠN', 'HỘI TỤ - KẾT TINH - TỎA SÁNG', 'Xã Yên Bình - Tỉnh Lạng Sơn', '(0205) 3885.6789', 'thcsyenbinh.huulung@langson.edu.vn', '/images/school-logo.jpg', '/images/school-banner.png')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.articles (id, title, slug, category_id, category_name, summary, content, image, author, is_featured, views) VALUES
(1, 'Lễ kết nạp Đảng viên mới cho cán bộ giáo viên THCS Yên Bình', 'le-ket-nap-dang-vien-moi', 1, 'Tin tức - Sự kiện', 'Vào lúc 14 giờ 00, Chi bộ trường THCS Yên Bình đã long trọng tổ chức Lễ kết nạp Đảng viên cho giáo viên ưu tú có nhiều thành tích xuất sắc.', 'Chiều ngày 04/08/2026, Chi bộ Trường THCS Yên Bình đã tiến hành Lễ kết nạp Đảng viên cho quần chúng ưu tú.', 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&q=80', 'Ban Biên Tập THCS Yên Bình', 1, 1250)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.documents (id, code, title, category, issue_date, signer, views, downloads) VALUES
(1, 'TT07/2026/TT-BGDĐT', 'Thông tư 07/2026/TT-BGDĐT về Phổ cập giáo dục THCS và Xóa mù chữ năm 2026', 'Thông tư BGD&ĐT', '04/08/2026', 'Bộ trưởng BGD&ĐT', 4830, 1722),
(2, 'TT42/2025/TT-BGDĐT', 'Quy chế công nhận trường Trung học đạt chuẩn quốc gia cấp độ 2', 'Quy chế Nhà trường', '15/12/2025', 'Thứ trưởng BGD&ĐT', 3410, 1205)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.videos (id, title, youtube_id, thumbnail_url, views) VALUES
(1, 'Hoạt động trải nghiệm sáng tạo STEM môn Sinh - Hóa tại THCS Yên Bình', 'dQw4w9WgXcQ', 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&q=80', 920)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.albums (id, title, date, photos_count, cover, description) VALUES
(1, 'Lễ Khai giảng năm học mới 2026 - 2027 trường THCS Yên Bình', '05/09/2026', 24, 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&q=80', 'Những khoảnh khắc đáng nhớ trong ngày khai trường THCS Yên Bình')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.resources (id, title, type, subject, author, date, downloads) VALUES
(1, 'Bộ đề thi Giữa Kỳ 1 môn Toán lớp 9 năm học 2026-2027 kèm đáp án', 'Đề thi & Đáp án', 'Toán 9', 'Tổ Chuyên Môn Toán', '08/08/2026', 450)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.schedules (id, day_title, time_slot, content, leader) VALUES
(1, 'Thứ Hai (10/08)', '07:30', 'Chào cờ toàn trường - Phổ biến kế hoạch học tập tuần mới', 'Ban Giám Hiệu'),
(2, 'Thứ Tư (12/08)', '14:00', 'Họp Chuyên môn Tổ Tự nhiên & Xã hội', 'Tổ Trưởng Chuyên Môn')
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.announcements (id, content, priority, is_active) VALUES
(1, 'Chào mừng quý thầy cô, phụ huynh và các em học sinh truy cập Cổng thông tin điện tử Trường THCS Yên Bình, xã Yên Bình, tỉnh Lạng Sơn!', 1, 1)
ON CONFLICT (id) DO NOTHING;
